version: 2
updates:
  # be
  - package-ecosystem: cargo
    directory: be
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: chore(be)

  # fe
  - package-ecosystem: npm
    directory: fe
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: chore(fe)
