services:
  be:
    build:
      context: ./be
    ports:
      - 127.0.0.1:8080:8080
  fe:
    build:
      context: ./fe
      args:
        PUBLIC_API_URL_ARG: http://localhost:8080
    ports:
      - 5173:80
