[package]
name = "be"
version = "1.0.0"
edition = "2021"
license = "CC0-1.0"
description = "Backend service for the k-in-a-row game."
default-run = "server"

[[bin]]
name = "server"

[profile.dev]
opt-level = 3
overflow-checks = false

[profile.test]
opt-level = 3
overflow-checks = false

[dependencies]
actix-web = "4.2"
actix-rt = "2.7"
serde = { version = "1.0.147", features = ["derive"] }
rand = "0.8.5"
