name: build-images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-fe:
    name: Build frontend image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fe
    env:
      PUBLIC_API_URL: 'http://localhost:8080'
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -t k-in-a-row/fe:latest .
  build-run-be:
    name: Build image and start a container from it
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./be
    env:
      API_HOST_PORT: 8080
    steps:
      - uses: actions/checkout@v3
      - name: Install curl
        run: |
          sudo apt-get update && sudo apt-get install -y curl
      - name: Build image
        run: |
          docker build -t k-in-a-row/be:latest .
      # Check that there aren't runtime errors when starting a container
      - name: Start container
        run: |
          docker run -d -p 127.0.0.1:$API_HOST_PORT:8080 --rm k-in-a-row/be
      - name: Wait for container to start
        run: |
          ./scripts/poll_next_move.sh $API_HOST_PORT
