name: deploy-be

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  tests:
    uses: ./.github/workflows/tests-be.yml
  build:
    name: Build an image and push to GCR
    needs: tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./be
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        env:
          PROJECT_ID: '${{ secrets.GOOGLE_PROJECT_ID }}'
          SERVICE_NAME: '${{ secrets.GOOGLE_SERVICE_NAME }}'
        run: |
          docker build -t "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" .
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_FILE }}'
      - name: Push image to gcr.io
        env:
          PROJECT_ID: '${{ secrets.GOOGLE_PROJECT_ID }}'
          SERVICE_NAME: '${{ secrets.GOOGLE_SERVICE_NAME }}'
        run: |
          docker push "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
  deploy:
    name: Deployment to Google Cloud Run
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./be
    steps:
      - uses: actions/checkout@v3
      - name: Fail for now
        run: exit 1
