name: tests-be

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Backend lints
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./be
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup component add rustfmt   
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: Lint
        run: |
          cargo check
          cargo fmt -- --check
          cargo clippy -- -D warnings
  test:
    name: Backend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./be
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update
      - name: Test
        run: |
          cargo test --bin server
  cargo-build:
    name: Backend build
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./be
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update
      - name: Build
        run: |
          cargo build --verbose
