name: tests-be

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  check:
    name: Backend lints, build checks and tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./be
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup component add rustfmt   
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version    
      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings        
      - name: Test
        run: |
          cargo check
          cargo test    
      - name: Build
        run: |
          cargo build --verbose
